### ISSUE TITLE
Allow passing of the Model search text parameter via URL

### ISSUE THREAD

**Issue by JustasB** [MetaCell/geppetto-scidash#106]
I would like a feature where text that would be typed in the "Model" text box could be passed as a url parameter.

For example, the following url: 

`http://scidash.a88dc6aa.svc.dockerapp.io:8000/?model=ReducedModel`

Would open the SciDash page with "ReducedModel" pre-typed into the Model filter text box and show a list of tests for the "ReducedModel".

CC: @scrook @rgerkin

**Comment by rgerkin** [comment]
@gidili This would be used to help link with NeuroML-DB.

**Comment by gidili** [comment]
@rgerkin @JustasB this should be fairly easy to implement, could be in theory done for any of the text filters we have (pre-populate based on querystring params) - let's discuss on Tuesday 👍
