### ISSUE TITLE
Neuronunit model validation

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#137]
https://github.com/scidash/neuronunit/issues/186

**Comment by rgerkin** [comment]
Partly implemented in 7952585e8459fc10d36918663a443fdad2ceb91b

**Comment by rgerkin** [comment]
Not exhaustive, but see scidash/neurounit#186 which is how I intend to do things.  In that example, the method `has_pulse_generator` of the LEMSModel class checks for a particular (standard?) way that somatic input current would be implemented in the NeuroML files.  A dictionary `extra_capability_checks` (a new sciunit model attribute) has claimed capabilities as keys and these kinds of checking methods as values.  Any capability not in the dictionary (but present as a parent class of the model) is assumed to always be implemented successfully in the model class definition.
