### ISSUE TITLE
Change Default Date Range to get last N records, not last N months

### ISSUE THREAD

**Issue by rgerkin** [MetaCell/geppetto-scidash#152]
The OpenWorm examples I uploaded a few months ago aren't visible on the site unless the date range is changed, because they fall outside the default date range window.  But right now there aren't enough records to make it worth excluding any of them from the initially loaded population.  Can we change the default date range so that it gets at least N records (N~100 or whatever is reasonable to load).  This probably means computing the date range dynamically when the page is loaded to set the earliest start date to whatever will get at least N records.

**Comment by gidili** [comment]
Thanks for creating this @rgerkin and agreed, we had discussed this and your proposal I think is the way to go - @jrmartin will look into it this week
