### ISSUE TITLE
Sample JSON to be used for uploading data

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#21]
A sample of the json SciUnit will out put and that will be used for populating the database with test scores for a given SciUnit run.

**Comment by gidili** [comment]
@rgerkin is tracking the issue here ==> https://github.com/scidash/sciunit/issues/49

**Comment by rgerkin** [comment]
@gidili See [here](https://github.com/scidash/neuronunit/blob/master/neuronunit/unit_test/serialization_test.ipynb) for an example.  
You will need the latest versions of `sciunit:master` and` neuronunit:master`

**Comment by gidili** [comment]
@rgerkin thanks this looks super useful! Will let you know if any questions 👍
