### ISSUE TITLE
Old SciDash work

### ISSUE THREAD

**Issue by rgerkin** [MetaCell/geppetto-scidash#22]
I forgot about this but a couple of years ago I started on a SciDash Django project with GitHub integration.  I can't really recall how much it does, but there might be some useful code here to take a look at, particularly for modelling the relationships between objects, and also for tracking SciDash stuff on GitHub.  This was back when my vision was for all SciDash-related repositories to be forks of one upstream SciDash repository so I could easily track them.  Let me know if you'd like to take a look and see if there is anything here you might like to use, and I can help out.  Ironically enough, this is a mercurial repository:  
https://bitbucket.org/rgerkin/scidash

**Comment by gidili** [comment]
@rgerkin definitely useful for inspiration on the data modelling side of things - thanks for pointing us to it!

**Comment by rgerkin** [comment]
The object model is probably out of date, but we can go over it together some time.

**Comment by gidili** [comment]
I thought so no worries 👍  we have started on the new object models and I am planning to review with you next time we meet (I will be traveling next week so right after).

**Comment by gidili** [comment]
Latest models available on the [scidash repo](https://github.com/MetaCell/scidash/blob/development/scidash_models.png) 

I would suggest we close this issue and open another issue for discussing the new models when necessary.
