### ISSUE TITLE
List of capabilities to run checks on when registering model

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#227]

**Comment by rgerkin** [comment]
The new cell 10 in [this familiar notebook](https://github.com/scidash/neuronunit/blob/dash/neuronunit/unit_test/nml_extra_capability_check.ipynb) should handle this.  The new `failed_capability_checks` method will give you a list of capabilities that appear to be unimplemented, after checking using the function specified in `extra_capability_checks`.  If the model class is written correctly, this should then be an empty list if and only if all of these checks pass.  So you can use an empty `failed_capability_checks` as evidence of compatibility.  

As always, both sciunit and neurounit should be updated to the head of the dash branch.
