### ISSUE TITLE
Example of how to pull out capabilities from a model class and run checks

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#228]

**Comment by rgerkin** [comment]
This is pretty straightforward now following from the example in #227.  For every candidate model (i.e. the list of all the models you have), instantiate it (e.g. using a LEMS file), then keep that candidate mode only if it's `failed_extra_capabilities` property is empty, e.g.:  
```
model_classes_to_keep = [cls for cls in all_model_classes if not cls(LEMS_file_path).failed_extra_capabilities]
```
