### ISSUE TITLE
Test remote dependency resolution on neuronunit

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#238]

**Comment by rgerkin** [comment]
The `LEMSModel` (of which `ReducedModel` is a subclass) has a method `get_nml_paths` which will get all paths (with .nml extensions) corresponding to Include directives in the base NeuroML/LEMS files.    It has a keyword arguments `absolute` which defaults to `True`, making these absolute file paths on disk (the same disk where the original file to instantiate the model was found).  But if `absolute` is `False` then these will be relative paths, so they should work with `urljoin`, e.g.:
```
relative_paths = model.get_nml_paths(absolute=False)
from urllib.parse import urljoin
new_urls = [urljoin(original_url, relative_path) for relative_path in relative_paths]
```
I didn't test it, but something like this should work.  Then you could use the `new_urls` to download nml files as well, and you will have to make sure that they in the correct relative location to the original file, but the relative paths should give you a good guide about how to do that (in most cases they will just be right next to the original file).

**Comment by gidili** [comment]
Very nice @rgerkin we will test with absolute set to False and report back! This is already how the java nml model interpreter works so there should be no need of downloading the actual files if neuronunit can deal with the import as relative remote paths.
