### ISSUE TITLE
Review scidash + geppetto-scidash instructions

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#24]

**Comment by rgerkin** [comment]
Remind me what you need me to do here?

**Comment by gidili** [comment]
@rgerkin this is basically a placeholder for you to review / test instruction for installing the whole django app + db + scidash geppetto extension since you expressed interest in doing so. 

But I want to detail the issue first so you know where to grab instructions and what's what - also there is not much to see "in action" at the moment just a bunch of unit tests for the data access layer, so basically you can leave this parked for the moment and I'll ping you with more info soon.
