### ISSUE TITLE
Integrate schema names into scidash UI using observation_schema_names

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#244]
-  [ ] schema to have name and short description
- [ ] observation params and test params to have descriptions (to be shown on the UI as tooltips)

**Comment by gidili** [comment]
@rgerkin added the items we discussed in the description

**Comment by rgerkin** [comment]
In latest dash branches, test classes have new `.observation_schema_names()` method that will either return an empty list (for single schemas), a list of default schema names ("Schema 1", "Schema 2", ...) for lists of schemas that have no names (as was the case for most NeuronUnit tests previously), or a list of actual schema names.  These actual schema names are provided through SciUnit by using a new optional format for the list of schemas.  The old format was [schema1, schema2, ...], which is also still accepted.  The new format is [(schema_name1, schema1), (schema_name2, schema2), ...], which is how the base `VmTest` schema now looks.

**Comment by gidili** [comment]
Got it, thanks @rgerkin we will work on integrating this
