### ISSUE TITLE
Validate json / suggest new version 

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#26]

**Comment by gidili** [comment]
Json we are currently using to test against is [here](https://github.com/MetaCell/scidash/blob/development/json_sample.json).

**Comment by rgerkin** [comment]
Can you describe how this was produced?  Was it from something related to the serialization notebook I provided?  Did it use the Model.json property?

**Comment by gidili** [comment]
@rgerkin this was produced manually taking the serialisation of the score object (which seems to be the main entity that should contain info / reference about everything everything else) from your serialization notebook example but augmented with things we expected from the model definition that were missing, see differences below (I renamed some properties to highlight the real diff): 

<img width="1435" alt="screenshot 2017-11-16 12 53 16" src="https://user-images.githubusercontent.com/68134/32892192-4eb19908-cacd-11e7-8a2b-d8f61897d505.png">

This is basically showing that we had to add info about model class, test class and test suite so that we could populate the db with all the info when uploading. This is flowing from the requirements we worked on together that say we should be able to show that information. 

It may be that some of these things we added  can be suppressed in particular circumstances or that we want to drop some of them for the time being - basically we need to work together to converge to something that can be mapped 1:1 from the serialization output to the db schema and we can use this issue to drive that conversation.

**Comment by rgerkin** [comment]
I think it makes sense for me to update the python implementation of the serialization to match the richer version that you are producing here.

**Comment by rgerkin** [comment]
Currently I have no way for a single Score to know which TestSuite, if any, a Score's Test came from.  In most cases, the Test is independent of the TestSuite, although in some cases hooks are set on the TestSuite which make the simulation parameters in one Test dependent on the outcome of a previous Test in the same suite.  In the example in the serialization notebook, I use one isolated Test that not only does not come from a suite, but has no simulation parameters.  Normally, those simulation parameters would be among the attributes of the Test that should show up when it is serialized, so even if they were set by TestSuite hooks, the serialized version should nonetheless contain all the relevant information.  

My larger point is I'm not sure yet whether we need to know what TestSuite a given Score came from.

**Comment by gidili** [comment]
@rgerkin it would be great if those nested objects (I think we are talking about model class and test class) are included when score is serialised, that way we would have a very close match between the two jsons that would allow us to rely on the serialised score object to have all the data we need to populate the db... exception made for test suite data maybe.

The suite data may or may not be there (a test may or may not be associated to a suite) so I would say that is definitely optional but you also make a good point that the relationship probably needs to be the other way around (suite having a foreign key to the test and not test to suite). 

This also came up on this other discussion on the data model and we are taking steps to address it https://github.com/MetaCell/geppetto-scidash/issues/25.
