### ISSUE TITLE
Example of how to run OSB protocols 

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#27]

**Comment by gidili** [comment]
@rgerkin 

Quick guide on how to see OSB protocols in action below:

1. Login into OSB (or create an account first then login)
2. Go to the [HH example](http://opensourcebrain.org/projects/hodgkin-huxley-tutorial?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopenworm%2Fhodgkin_huxley_tutorial%2Fmaster%2FTutorial%2FSource%2FHHCellNetwork.net.nml) 
3. Hit the "star" button at the top to persist to your HH model
![screenshot 2017-11-14 15 54 08](https://user-images.githubusercontent.com/68134/32796442-ae976aea-c966-11e7-8028-cd3c11447aa0.png)
4. Go to your OSB home (click OSB logo on top left) then "Your models" tab
5. HH sample should show up in the dashboard - double click it and the project will open
![screenshot 2017-11-14 18 03 13](https://user-images.githubusercontent.com/68134/32796255-1f418e8e-c966-11e7-81c5-12f91d736314.png)
6. Click on the control panel icon on the left bar to open the control panel, then click on the parameters filter from the filter buttons at the top (use tooltips to tell what's what) - 4 pages of parameters will show, any of them can be edited (it auto saves upon editing)
![screenshot 2017-11-14 17 59 45](https://user-images.githubusercontent.com/68134/32796354-6ae6dc68-c966-11e7-969b-ea73f0c42bf6.png)
7. Now click ESC or anywhere outside the control panel to close it
8. Go to the run menu and click on "Add & Run Protocol"
![screenshot 2017-11-14 16 11 01](https://user-images.githubusercontent.com/68134/32796454-b7df83ee-c966-11e7-8cc7-6ddf36c3771f.png)
9. The add protocol dialog will appear where you can set protocol parameters
![screenshot 2017-11-14 16 11 13](https://user-images.githubusercontent.com/68134/32796472-c8266ca4-c966-11e7-951c-647878a91d4f.png)
10. When ready hit "Submit" (tip: set simulation duration to something shorter than 600ms otherwise it will take a while to complete... 150ms should show some spikes), the top left OSB will start spinning meaning the protocol is being created and queued up for simulation - this dialog will appear when done
![screenshot 2017-11-14 16 12 01](https://user-images.githubusercontent.com/68134/32796540-f291c2d6-c966-11e7-885f-41d7ab0289bb.png)
11. Open the experiments tab on the console at the bottom of the screen and you should see your experiments being executed (green is done, yellow running and blue queued up)
![screenshot 2017-11-14 16 12 30](https://user-images.githubusercontent.com/68134/32796629-3ab6e79e-c967-11e7-87eb-32b508478491.png)
12. Upon completion of all the experiments the protocol summary dialog will come up (you can also open it from the results menu hitting "Show protocol summary")
![screenshot 2017-11-14 16 17 01](https://user-images.githubusercontent.com/68134/32796683-6092fdb8-c967-11e7-97af-ff8f36cf42c2.png)
13. Hit the "plot data" button (with he graph icon) in the protocol summary menu to plot results
![screenshot 2017-11-14 17 53 46](https://user-images.githubusercontent.com/68134/32796727-8b3be19c-c967-11e7-9a27-a2af545d421c.png)

**Comment by gidili** [comment]
@rgerkin following form our discussion every experiment in my opinion the protocol creates a "test suite", and each experiment maps to a test instance but possibly the same model instance because the model parameters are the same and only the simulation parameters are changing in each experiment. A score could be associated to each experiment (and to the protocol) if observations were to be provided for the different combinations of simulation parameter values (pulse start/stop, amplitude start/stop, timestep, duration).

**Comment by rgerkin** [comment]
Thanks, it looks good.  It would be great to reuse this as much as possible for SciDash.

**Comment by gidili** [comment]
@rgerkin I am starting to think so too - if so a case could be made to use SciDash only as a viewer of test scores (work that we are doing now) and the test scores end up in SciDash either from uploading after running tests locally or triggered from OSB and then running on the SciDash server. If we want to explore this route more seriously we need to start pulling into the conversation the OSB team soon.
