### ISSUE TITLE
Watched variables discussion

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#272]
Which variables to watch and who should dictate this?

Options:

- watch all state variables
- only watch variables that a certain test requires to be there, hardcode implementation mapping test classes to logic
- only watch variables encoded in the test class somehow (how?)
- Others?

**Comment by rgerkin** [comment]
Let's do it like this:  
- A model instance will optionally have a `recorded_variables` attribute.  
- In your simulation backend, you check to see if exists.  
  - If it does not, you record them all.  
  - If it does, and is None, you record them all.  
  - If it does and is a list, you record only those in the list.  
  - If it is anything else, raise an Exception.  
 - When instantiating the model on the server, the user will be able to select or de-select state variables from the model's variable list.  This will update the `recorded_variables` attribute for that model instance (not for the class as a whole).  By default I will make the attribute `None`, so be sure to check if it is a list before appending.
