### ISSUE TITLE
How to represent aggregate score for test-instance with a single scalar?

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#28]
Hi @rgerkin question for you:

Let's say we have a test instance of class InputResistanceTest with score as such:

<img width="196" alt="screenshot 2017-11-30 13 15 47" src="https://user-images.githubusercontent.com/68134/33432619-9b55866c-d5d0-11e7-9b1e-2e377892ddd7.png">

As I understand it the score here is solely represented by the background color mapping to whatever values are relevant to the test (in this case Z). What's the best way to represent the aggregate score for all these values in terms of a single scalar number (that we can then associate to the same background color)? Would a simple average do?

The idea (as we discussed before but mainly for suites) is that we would just display a single scalar/color combination for a given test-instance row and then upon click we could show the score breakdown (possibly similar as the image attached above).

**Comment by rgerkin** [comment]
Here you appear to be showing scores for 4 different model instances.  I'm not sure when you would want to aggregate those.  Are you instead referring to the situation where you want to aggregate scores for one model instance across test instances?  

In that case I use a value called `sort_key`, which is an attribute of every score (no matter what it's type), and which is always a value between 0 and 1, where 1 is the best.  This allows me to aggregate across scores of the same type or of different types, by simply averaging the corresponding sort_keys.  The `mean` property of a ScoreArray [does just that](https://github.com/scidash/sciunit/blob/master/sciunit/__init__.py#L1038).  The exact mapping between a score of a given type and its sort_key is subject to change, but that attribute is guaranteed to exist and be between 0 and 1, so it should make it pretty easy to aggregate however you want.

**Comment by gidili** [comment]
@rgerkin yes this is exposing some of my own confusion when I started thinking about how we are going to represent scores in the UI. 

Let me recap to see if I understand correctly now:

So basically (in the first cell) -1.04 is the score of Type Z for that test instance and that there should also be a score_key attribute on the score itself with a normalized value between 0 and 1.

While for a test suite the way to obtain an aggregate score is to average the store_key values (mean property of ScoreArray). 

If the above is correct, now questions for you:
- should we have the score_key as part of the json serialized attributes when serailizing score (not there now)
- I think we also need the score_type as a serialized attribute (also not there now) as we are planning to display in the UI from our previous discussions

Btw the [serialization notebook example](https://github.com/scidash/neuronunit/blob/master/neuronunit/unit_test/serialization_test.ipynb) seems gone from master, any chance of having it back? 😃

**Comment by rgerkin** [comment]
Yes, the score is type sciunit.scores.ZScore, with a `sort_key` attribute (whose value is determined by a class method that converts the `score` attribute into a `sort_key`).  

Yes, you should probably have both of these attributes added to the serialization.  

The notebook examples is still in dev [here](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/serialization_test.ipynb).  I had to do a hard reset on master that took a few things previously merged from dev back out, but it shouldn't much matter because all of this only relies on recent changes to sciunit which are in its master already, not to neuronunit (the example is in the neuronunit repo because it uses neuronunit models).

**Comment by gidili** [comment]
Issue created on scitunit to track modification to the json serilized representation for score https://github.com/scidash/sciunit/issues/64
