### ISSUE TITLE
Filter by tag returning duplicate results, not showing autosuggest for existing tags

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#288]

**Comment by gidili** [comment]
Need to make sure it's actual duplicates and not simply records that look identical

**Comment by rgerkin** [comment]
The specific case we saw was when there was a single test that has any tags with the letter "g", but it had two such tags with that letter, e.g. "Big" and "Large".  Then when you type "g" in the tag search, you see that test twice.

**Comment by gidili** [comment]
Thanks for clarifying @rgerkin ! 👍
