### ISSUE TITLE
Mail setup for password reset (and future notifications)

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#333]

**Comment by gidili** [comment]
Hi @rgerkin do you have a mail associated to scidash.org that we can use for sending password reset messages? And if not, can we set something up - can be any mail you wanna use really and the same mail address / server can be used in the future when we add notifications etc if any.

**Comment by rgerkin** [comment]
Do I have to run a mail server on the server, or can I just make a gmail account, associate it with e.g. admin@scidash.org, and forward that to the gmail account?  Can you send through gmail smtp?

**Comment by gidili** [comment]
@rgerkin yes any gmail should do 👌

**Comment by rgerkin** [comment]
@gidili 
scidash.asu@gmail.com

**Comment by rgerkin** [comment]
I tried scidash.admin, but Google didn't allow that, probably to prevent phishing with email addresses that have "admin" in them.

**Comment by gidili** [comment]
Thanks @rgerkin, perfect 👍
