### ISSUE TITLE
Json for score color coding 

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#34]
Hey @rgerkin can we get a link to the latest version of the score color coding that you showed me a while back and that I believe from our last conversation will map the sort_key to the desired color for the given score?

**Comment by rgerkin** [comment]
The call stack looks like this:  
The score's [`color` method](https://github.com/scidash/sciunit/blob/dev/sciunit/__init__.py#L865) uses the scores' `sort_key` (by default) and then calls it's [`value_color` method](https://github.com/scidash/sciunit/blob/dev/sciunit/__init__.py#L871), which looks up the user-configured color values using the [`config_get` function](https://github.com/scidash/sciunit/blob/dev/sciunit/__init__.py#L54) which looks for a `config.json` file (e.g. [here](https://github.com/scidash/sciunit/blob/dev/sciunit/config.json) or uses hard-coded defaults.   Those values are used by `value_color` to build the colormap.  

Note that I am refactoring sciunit and moving a lot of stuff out of init (see the code-climate branch) but I can probably dig into your code base and make the necessary fixes at some point down the road.  I won't push this kind of change to pypi for a while, though, so no need to worry.  

Also, note that my scheme for coloring cells in the Jupyter notebooks is likely to change to reflect the recent ability of Pandas (sciunit.ScoreMatrix is a subclass of pandas.DataFrame) to have CSS stylers mapped to individual dataframe entries.  So in the future my code will look more like this:  

![capture](https://user-images.githubusercontent.com/549787/35832135-5b2eca42-0a89-11e8-9545-c30372677778.PNG)

Except that it will still do the same reading of the config file, etc. to figure out the colormap values to use for the low and high of the range.  And I still plan to use red/yellow/green; the red/white/blue example above is just what I had available.

**Comment by gidili** [comment]
After out chat, we are gonna put together a simple json config mapping figure range to color range and calculate interpolations based on those extremities. 

Standard color mapping will be red to green but we also discussed an alternate "togglable" color coding mapping color-blind friendly (yellow to blue) based on this figure below @scrook provided.

![professionaldevelopment_figure_1](https://user-images.githubusercontent.com/68134/35910982-532771e2-0bf0-11e8-92fd-51f5ab02d362.jpg)

Paper here: https://arxiv.org/ftp/arxiv/papers/1712/1712.01662.pdf
