### ISSUE TITLE
Add test info as a dialog upon clicking on test name (make it a link) on the test score page

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#355]
Test Info
I thought I brought this up a few months ago, but on the Test Scores page;
-- clicking a model name shows a lightbox with model info
-- clicking a score shows a lightbox with model info and test info
-- clicking a test name does nothing (no link)
It seems straightforward for clicking the test to bring up a lightbox with test info, since you must already have a function that generates the test info in the lightbox when clicking the score.

**Comment by gidili** [comment]
This should be straightforward following the pattern we have for model and score dialogs, considering we already have a react component to show test instance info. It requires some basic react and redux  knowledge on the frontend but it's a fairly straightforward improvement.

**Comment by ddelpiano** [comment]
done with https://github.com/MetaCell/geppetto-scidash/pull/368

**Comment by gidili** [comment]
Re-opening as this was killing performance on the main score view so we rolled it back for now. Need to rethink the logic.

**Comment by ddelpiano** [comment]
mainly to re-work state and reducer handled by redux to provide the info to the component, I tried to hack it the first time to have a quick win but it was not feasible and was impacting performances due to the component state.

**Comment by rgerkin** [comment]
Still valuable, if it can be done in a roughly performance-neutral way.
