### ISSUE TITLE
Add model info dialog on models page (same as we have in scores page)

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#365]
On the test scores page a model name can be clicked to give the model instance lightbox.  But on the models page there is no such link.  Could this be added?  The only concern here would be that some things like instance run parameters might not exist yet because the model would not have been run.  But it would be nice to see other things that are in that lightbox like capabilities.  It would also make for a more consistent UI.

**Comment by gidili** [comment]
Doable and not a lot of work as we already have the model info component.

**Comment by ddelpiano** [comment]
done with https://github.com/MetaCell/geppetto-scidash/pull/370
