### ISSUE TITLE
Score Type disappeared

### ISSUE THREAD

**Issue by rgerkin** [MetaCell/geppetto-scidash#373]
In the current build, I can't see the Score Type in the test scores page:

![Screen Shot 2019-08-22 at 9 00 27 AM](https://user-images.githubusercontent.com/549787/63530436-51b11900-c4bb-11e9-9ac8-ba47f092e5b5.png)

When I click on the score I can see the score type in the lightbox, so it isn't null, but it isn't showing up in the main view.

**Comment by gidili** [comment]
We addressed this in the latest build.
