### ISSUE TITLE
Autocomplete on filters not working consistently on all fields (seems to be only showing fields present on first load)

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#377]

**Comment by gidili** [comment]
Investigate if this can be reproduced

**Comment by rgerkin** [comment]
What does "fields present on first load" mean?  Aren't all the fields the same with every load?  Or do you mean "data present on first load"?

**Comment by ddelpiano** [comment]
@rgerkin data present on first load is what @gidili meant, experienced this myself as well.
