### ISSUE TITLE
Filter values are not being reset when switching from test score view to suite view causing some confusion

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#378]
This is particularly confusing when fields that are not filterable on the suite view are retaining filters from the tests score view. Simplest solution here is to blank all the fields.

**Comment by rgerkin** [comment]
Maybe blank all except set the date field to do the last N thing.  I could also imagine a case where a user finds some set of filters really important and gets annoyed that they go away when switching views.  Let's look at this and think through cases where it would be confusing to keep them vs annoying to reset them and see if a pattern emerges that leads to a logical solution.

**Comment by gidili** [comment]
The biggest issue here is that filters that exist in score view but do not exist in the suite view are retained and cannot be blanked once the user switched to the suite view, so no records are showing up because of a retained filter that should be blanked as it doesn't apply to the suites page. 

cc: @jrmartin this should give you ideas for how to implement the automated test for this buggy behaviour, but feel free to reach out for any clarifications

**Comment by ddelpiano** [comment]
issue noticed during testing:

- login as admin
- I am in the test scores view and I blank the owner filter and then fill it with the string "justasb" so I can see all the scores that belongs to this user
- I move to suites scores view and everything is fine.
- I move to the tests view, the owner filter here is blanked
- If I go back to the test scores page from here the owner filter is now filled with my user (admin).

**Comment by zsinnema** [comment]
> issue noticed during testing:
> 
> * login as admin
> * I am in the test scores view and I blank the owner filter and then fill it with the string "justasb" so I can see all the scores that belongs to this user
> * I move to suites scores view and everything is fine.
> * I move to the tests view, the owner filter here is blanked
> * If I go back to the test scores page from here the owner filter is now filled with my user (admin).

This was related to #428
and fixed here
