### ISSUE TITLE
Improve auto-load time range, right now it's not incrementally going back to look for older records if none are found

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#381]
Might be just a matter of configuring settings to look even more in the past if no recent records are found

**Comment by gidili** [comment]
This needs to be changed to look for TOP N records descending by date and set the default date based on what comes back

**Comment by rgerkin** [comment]
Yes, and N should be determined by some performance tradeoff.  This is my nominee for top issue, if only because any deployment that does not have this will look empty to the untrained user!

Bonus: N is computed dynamically according to some latency/speed calculation, e.g. from first file load.

**Comment by rgerkin** [comment]
Does the current date range have something to do with [this](https://github.com/MetaCell/geppetto-scidash/blob/5752f08db88f3a3cb477775dc0fffef59481c2ba/services/InitialStateService.js#L79)?

**Comment by ddelpiano** [comment]
As per sprint meeting, this comes with reduce bandwidth in this sprint and if we can find a quick fix in ~2 hours we can push it in this sprint, differently will be top-priority for the following.

**Comment by gidili** [comment]
> Does the current date range have something to do with [this](https://github.com/MetaCell/geppetto-scidash/blob/5752f08db88f3a3cb477775dc0fffef59481c2ba/services/InitialStateService.js#L79)?

@rgerkin most likely! We need to follow that thread and see where the value is coming from to inform a possible solution or even to evaluate if it's worth doing a quick fix or if it's easier to just go straight for a proper solution

**Comment by zsinnema** [comment]
@gidili the from/to range is in quarter steps (3 months, 6 months, etc). Is this a functional requirement? If not then I suggest I change the backend to do a search for the first N (configuration setting) records and then return this period. In this case it doesn't matter how much time is between "today" and the last scores.

**Comment by gidili** [comment]
@zsinnema yes I agree with that suggestion in fact from my thought (from a post above) was: 

> This needs to be changed to look for TOP N records descending by date and set the default date (in the filters) based on what comes back

Which I think is exactly what you are suggesting. The functionality is the way it is for "historical" reasons (it was a shortcut and I take the blame 🙋‍♂) but I think this is a better solution.

**Comment by rgerkin** [comment]
Yes, all we need is Top N when determining the default date, right?  I don't see any reason to impose any date filter on the backend until the user specifies one in the UI.
