### ISSUE TITLE
Create test plan to model automated tests against

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#391]

**Comment by rgerkin** [comment]
Is the test plan an informal document describing what we want to test?  Or is it something structured and machine-readable?

**Comment by ddelpiano** [comment]
@rgerkin this will be an informal document describing in details the critical path that the automated testing will cover.

**Comment by gidili** [comment]
We can start with a google doc to have a blueprint to start implementing tests and then consider if it makes sense to move to something like [TestRail](https://www.gurock.com/testrail) that we have played with in the past.

**Comment by ddelpiano** [comment]
@rgerkin Here the first draft ready for review - https://docs.google.com/document/d/131-Ijr7w2tmnf7qGzGmFHRjTpPaIKJX266wga-6aTv0/

Thanks!
