### ISSUE TITLE
Improve deployment to remove all manual steps as much as possible

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#393]

**Comment by rgerkin** [comment]
For a cloud deployment on an image with Kubernetes, is it possible to do the whole deployment in one line?  If so, the only other deployment instructions would be how to get Kubernetes running on a local server, which is well-covered elsewhere and not needed here.

**Comment by ddelpiano** [comment]
@rgerkin sure, if more than one command is required we can always wrap this up in a python/bash script to get the one-liner solution.
