### ISSUE TITLE
Implement error handling on frontend

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#396]
Since the upgrade to React 16 done with the card #390 we need to:
- integrate the Sentry exception capture on the frontend
- bobble up all the error coming from pygeppetto-django / sciunit / neuronunit / django (already done in #395) and implement a dialog that will show to the user the error that come from the backend (imho we don't need the complete stack trace, but at least where the exception is generated so that we can identify where the issue come from).
- The dialog should have a button to that trigger a reload of the UI and another button that would let us open an issue on github in the geppetto-scidash repo (e.g. https://github.com/VirtualFlyBrain/geppetto-vfb/blob/55554f54de349724ff9629157461c0b88c35fd25/components/interface/ErrorCatcher.js#L50 )

**Comment by rgerkin** [comment]
It would be sufficient for these errors to be visible in the browser developer console (provided they are informative about the underlying Gepetto error).  

Having them also be shown in the browser itself (e.g. status update on the page) could be a separate issue, which would require discussion about how much error info a user should get to see.  For example, may underlying errors in Geppetto could simply map to a user message of "Simulator error; the developers have been notified".

**Comment by gidili** [comment]
@rgerkin This issue is about having a useful error in the score card ERROR field (both in the db and displayed in the dashboard with all the scores when you expand details) when the simulation is not successful - sometimes when the neuroml fails to parse we get fairly obscure errros back from the libraries we are using and these errors are sometimes completely opaque to a scidash user who knows nothing about lems components.
