### ISSUE TITLE
Page title says "scheduling" instead of "test scores" when redirecting after running from the Scheduling page

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#404]

**Comment by ddelpiano** [comment]
@rgerkin do you prefer to have this title update as soon as the records have a final state (either the simulation has been completed or failed) or simply to display in the title Test Scores as normally the view should display? (I would vote for the second, this is a redirect within the UI from one view to another after we run the tests, the user will see the interaction in that view anyway from the icons that will change from scheduled-to locked-to done).
The estimate is pending depending on the solution chosen, the second is less time consuming than the dynamic title changed, I am suggesting that for this reason as well. 
Thanks!

**Comment by rgerkin** [comment]
I honestly have no idea what this issue is about.  Can you make a screen capture of the scenario?  Or we can wait until the next meeting.

**Comment by gidili** [comment]
This is very simply a label that says the wrong thing at the top of the
page, says "scheduling" instead of Test scores after the redirection from
scheduling to test scores

**Comment by rgerkin** [comment]
I guess it should say "Test Scores" then.  See also #409.
