### ISSUE TITLE
Global filters not applied to the Tests and Models views

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#428]
This has been noticed during the test of feature/378.

1. Login as admin
2. Fromt the test scores page change the owner filter to filter "justasb"
3. Move to the scores page (everything here is fine).
4. Move to the Tests page, as you can see the owner filter is ignored, the Timestamp filter instead is right.
5. Move to the Models page, as you can see both the global filters owner and timestamp here are ignored.

Points 4 and 5 are the actual bug.

**Comment by zsinnema** [comment]
fixed in feature #378

**Comment by ddelpiano** [comment]
@zsinnema I can see this fixed for the tests view, however the models view still got the same issue, the filter boxes are not filled with the global as it happens in the tests, suites and tests scores views. Could you open a separate PR for this since the other has been already merged? Thx
