### ISSUE TITLE
Model creation / editing fails to validate the model from the URL (500 internal server error).

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#436]
Go to the model view, create a new model, fill the name a put the url of the model (e.g. https://github.com/ddelpiano/neuronunit/blob/dev/neuronunit/models/NeuroML2/LEMS_2007One.xml ).
Check the console and you will see that the response from the server is not valid.

**Comment by zsinnema** [comment]
relates to #437 

fixed in PR https://github.com/MetaCell/geppetto-scidash/pull/440
