### ISSUE TITLE
Editing existing Model fields don't update fields in Models Page without reloading the page

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/geppetto-scidash#438]
Step 1. Login to scidash
Step 2. Open Models Page from the sidebar
Step 3. Click on 'ellipsis' icon (3 dots icon) and then 'Edit' option
Step 4. Edit name, class or tag in existing model
Step 5. Click Save

The edited model is saved, but once you are back on the Models page view you don't see the changes you made reflected. User has to reload the page to see the changes made to the model.

**Comment by zsinnema** [comment]
fixed by #428
