### ISSUE TITLE
RuntimeTypeError at /api/parameters/

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/geppetto-scidash#448]
Step 1. Open Scidash, login and go to Models page
Step 2. Click plus sign for new model creation
Step 3. Enter valid source URL for model
Step 4. Runtime error is thrown in chrome console, 'Open' parameters button never becomes enabled and spinning wheel keeps going forver

![image](https://user-images.githubusercontent.com/4562825/72832011-93e8ad00-3c49-11ea-8a3d-1d57e292694f.png)

**Comment by zsinnema** [comment]
closed in PR https://github.com/MetaCell/geppetto-scidash/pull/440 which is already merged into development
