### ISSUE TITLE
Some test classes are displayed twice

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#450]
![Screenshot 2020-01-22 at 12 04 38](https://user-images.githubusercontent.com/37704177/72892820-6e25db80-3d0f-11ea-91d2-3ea9a09e7f5f.png)

As per screenshot, some test classes are repeated, we should have the same behaviour for all the classes.

**Comment by zsinnema** [comment]
relates to #449 and is fixed by #449
