### ISSUE TITLE
Editing Existing Test Doesn't Update Form with new Parameters

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/geppetto-scidash#456]
Step 1. Create a new Test using 'InputResistanceTest (neuronunit.tests.passive)'  class
Step 2. Fill in the form parameters
![Screenshot from 2020-01-29 07-54-37](https://user-images.githubusercontent.com/4562825/73362842-336ef680-426d-11ea-850d-84fa9bbff180.png)
Step 3. Save Test and you are back on tests page
Step 4. Edit existing test with different class than Step 1
Step 5. In Test editor, select class 'IVCurvePeakTest (neuronunit.tests.channel)'. 
Step 6. Parameters in form don't get updated to reflect new class, parameters for previous class are present. Parameters in form should be the ones in screenshot of Step 2
![Screenshot from 2020-01-29 07-54-09](https://user-images.githubusercontent.com/4562825/73362822-28b46180-426d-11ea-9323-fd3495b00e2d.png)

**Comment by zsinnema** [comment]
@jrmartin  when I do it and I choose InputResistanceTest (neuronunit.tests.druckmann2013) and switch back to IVCurvePeakTest everything works fine.
can you give me the class you use?
