### ISSUE TITLE
Fix travis tests

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#472]
- Following the integration of the UI testing with travis we noticed with the last run 4 tests failed.
- Since we still have 2 PRs with conflict to be merged that will bring more tests we need to wait for those PRs to be merged before to start with this card.
- The aim of this is to ensure that all the tests that fail at the moment should be fixed or either we have an explanation for the failure (and in that case we will take an action for the test itself, so either comment this or implement the fix required).

**Comment by jrmartin** [comment]
@ddelpiano Two of the four failing tests on travis are due to bug #473 , fixing that bug itself might take some hours.
