### ISSUE TITLE
Editing Name on Existing Model Doesn't Update Inmediately on Models Page After Save

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/geppetto-scidash#473]
Step 1. Create a new Model, name it Model1, save it
Step 2. You are back on Models page, edit Model1, change name to Model2 and save it
Step 3. Back on models page, you should see Model1 is now Model2, but instead you still see it named Model1. You need to refresh the page for the Models page to correctly show Model2.

This happens running scidash locally from docker, with python command and inside travis. It doesn't happen when on COD instance.

**Comment by jrmartin** [comment]
As per call with Dario, this bug is still happening.

**Comment by ddelpiano** [comment]
fixed here https://github.com/MetaCell/geppetto-scidash/commit/3f74abe7f4b5bc6197465a472ac54a3efe34f50a
