### ISSUE TITLE
Create a second codefresh instance to be used for testing

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#477]
As requested by Rick, we need to put in place a second codefresh / k8 instance in order to re-enable the continuous deployment.
The current instance used for the grant can be switched to deploy production when the new release will be ready.

**Comment by ddelpiano** [comment]
http://34.69.33.177:8000/

**Comment by rgerkin** [comment]
@ddelpiano so which one (IP) is the one for reviewers and which one is for people in the lab to test?

**Comment by gidili** [comment]
@rgerkin the one for the reviewers is unchanged, the new one is for testing
!
