### ISSUE TITLE
Lock the sciunit version installed

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#478]
Due to the improvements performed in the installation procedure, now the sciunit library comes for free during the installation of neuronunit.
However, this is locked to be installed from the dev branch (from the neuronunit requirements file), we need to lock this to a precise tag / branch in order to avoid misalignment between the 2 libraries.
We can:
- Specify this explicitely in our requirements file
- Allocate a specific branch in neuronunit that we will use for the release and in there push this change in the neuronunit requirements file

**Comment by rgerkin** [comment]
There is now a [metacell](/scidash/sciunit/tree/metacell) branch of sciunit, and I won't push to that unless necessary for this project.
