### ISSUE TITLE
Broken Sign Up Page

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/geppetto-scidash#491]
Steps.
1) Using development branch for geppetto-scidash, launch scidash
2) Click on 'Sign up' button
3) Fill in form with 'sign up' information
4) Submit

![image](https://user-images.githubusercontent.com/4562825/77365225-f4ac6880-6d12-11ea-979c-b97c9277433f.png)

**Comment by zsinnema** [comment]
Is it possible that one of the last database migrations went wrong. Especially this one: 0011_scidashuser_show_instructions.py
it addes the show_instructions column to the user table AND adds a default True
May be the default is not in your database
I checked it on the test server (k8s) and there everything is working fine.
this is the url to the test server: http://34.69.33.177:8000/
