### ISSUE TITLE
Test API and document issues / make API great again

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#499]
Scidash-API fix upload of scores / model/test matching logic + integration testing

Test notebooks to run : 
1) https://github.com/MetaCell/scidash-api/blob/master/test-sciunit-serialization-performance.ipynb (worked at some point)
2) https://github.com/MetaCell/scidash-api/blob/master/test-score-upload-from-sciunit.ipynb (worked before)
3) https://github.com/MetaCell/scidash-api/blob/master/test-suite-upload-from-sciunit.ipynb (worked before)

**Comment by zsinnema** [comment]
fixed all notebooks in schidash api
