### ISSUE TITLE
Simulator / simulation parameters details serialisation example

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#56]

**Comment by gidili** [comment]
Hi @rgerkin - would it be possible to add simulator (backend attribute on model instance?) / simulation parameter details (should be on test instance?) in any of the serialisation examples we have [here](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/serialization_test.ipynb) (or any other if it's more convenient)? 

We talked about this a few times and it's in the mockups for one of the detailed views but we realised we don't have seen a concrete example while we were doing it so we don't have mock data yet for it.

**Comment by rgerkin** [comment]
Added in [latest version](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/serialization_test.ipynb).

**Comment by gidili** [comment]
Thank you @rgerkin !
