### ISSUE TITLE
Change api method names to upload_test_score and upload_suite_score

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#82]

**Comment by rgerkin** [comment]
@gidili @NeZanyat 
[PEP style guidelines](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) suggest that function names should use underscores (snake_case) rather than camelCase.  So `upload_test_score` and `upload_suite_score` would be better.

**Comment by gidili** [comment]
@rgerkin yes that's already the case! My bad for having non python notation in the title (too many years working with other languages) 😄
