### ISSUE TITLE
Add instance id to sciunit / neuronunit serialization

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#90]

**Comment by gidili** [comment]
Hi @rgerkin we are working on https://github.com/MetaCell/geppetto-scidash/issues/57 and the class bit we can do but we need your help adding the instance id to the serialisation whenever you can do that.

**Comment by gidili** [comment]
@rgerkin maybe I should create this (and similar) issues on the sciunit repo? Let me know if that helps you keep track

**Comment by rgerkin** [comment]
Added to sciunit dev branch in scidash/sciunit@5c71f02
